apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: next-app
  namespace: aub-clubs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ sharedVars.hostName }}`) || PathPrefix(`/`)
      services:
        - kind: Service
          name: next-app
          port: 3000
          scheme: http
  tls:
    secretName: my-tls-cert
