# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: next-app-database-url
  namespace: aub-clubs
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-20"
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@cnpg-minimal-rw.postgres.svc.cluster.local:5432/postgres
