apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-minimal
  namespace: postgres
spec:
  # You may or may not want to do this... I'm enabling for simplicity
  enableSuperuserAccess: true
  instances: 1
  storage:
    size: 5Gi
  superuserSecret:
    name: cnpg-minimal-superuser
