name: image-ci

on:
  push:
    branches:
      - "main"
      - "staging"
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necessary to get all tags for IMAGE_TAG generation with git describe
          fetch-depth: 0

      - name: Generate Image Tag
        id: generate-image-tag
        run: |
          chmod +x operations/tag-gen.sh
          image_tag=$(./operations/tag-gen.sh)
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  build-tag-push:
    runs-on: ubuntu-latest
    needs: generate-image-tag
    strategy:
      matrix:
        include:
          - image: hamzarach69/aub-clubs-next
            dockerfile: Dockerfile
          - image: hamzarach69/aub-clubs-migrate
            dockerfile: Dockerfile.migrate
          - image: hamzarach69/aub-clubs-seed
            dockerfile: Dockerfile.seed

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        run: |
          chmod +x operations/build_image.sh
          ./operations/build_image.sh "${{ matrix.image }}" "${IMAGE_TAG}" "${{ matrix.dockerfile }}"

  update-tags:
    runs-on: ubuntu-latest
    needs: [generate-image-tag, build-tag-push]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Update Image Tags
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        run: |
          node operations/update_tags_json.js "${IMAGE_TAG}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          token: ${{ secrets.DEVOPS_DIRECTIVE_KUBERNETES_COURSE_GITHUB_ACTION_PAT }}
          title: "Update image tags to (${{ needs.generate-image-tag.outputs.image_tag }})"
